### ISSUE TITLE
details op home pagina veranderen

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#88]
- [x] Screen responsive maken van de foto's
- [x] afbeeldingen hoogte = hoogte van venster
- [x] Tekst op de foto weergeven
- [x] Logo toevoegen
- [x] Navigatie menu licht transparant met achtergrond afbeelding
- [x] footer niet static onderaan
- [x] niet zijdelings scrollen
- [x] Account acties zoals login of register niet in dropdown zetten. Te verborgen voor nieuwe en nieuwschierige mensen.
- [x] Search balk aanpassen zodat zoekknop en zoek vak tegen eklaar staan.
- [x] App reclame
- [ ] ~~Random images tonen als eerste foto? @WatchFriends/frontend-webdevelopers Wat denken jullie hiervan?~~

**Comment by HeinPauwelyn** [comment]
@michielzyde: enkele opmerkingingen over uw code:

Over onderstaande code in `app.component.scss`:

```scss
footer {
  margin-top: $footer-header-margin;
  background-color: $footer-color; // --> is zwart
  height: 50px;
  position: fixed;
  width: 100%;
  bottom: 0;

  p { // --> default achtergrond kleur: zwart
    text-align: center;
    padding: 85px;
    font-size: 20px;
  }
}
```
1. een zwarte actergrond met zwarte tekst is onleesbaar!
2. een footer ga je meestal niet onderaan een pagina gaan fixen. Dit omdat de content in de footer kan uitgebreid worden naar een verticaal menu... Kortom de footer zal later mss te hoog zijn om dan nog onderaan de pagina te fixen.
3. een padding van 85px zal niet goed tonen op kleinere schermen
